<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\EncryptionTrait;
use Carbon\Carbon;
use Illuminate\Foundation\Auth\User as Authenticatable;


class Customer extends Authenticatable
{
    use EncryptionTrait;

    protected $fillable =['name','email','password','active'];
    protected $appends = ['humans_date','id_hash'];

    protected $guard_name = 'web';

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::creating(function($model){
//            $model->name =  $model->firstName . ' ' . $model->familyName;
//        });
//    }
    public function getHumansDateAttribute()
    {
        return Carbon::parse($this->created_at)->diffForHumans();
    }
    function getIdHashAttribute()
    {
        return $this->encrypt($this->id);
    }

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }


}
