<?php

namespace App;

use App\Traits\EncryptionTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use EncryptionTrait;
    protected $table = 'news';

    protected $fillable = ['title', 'description', 'user_id', 'image','update_id', 'active','category_id'];

    protected $appends = ['humans_date', 'id_hash','url'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($news){
            $news->slug = str_slug($news->title, '-', config('locale'));
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getHumansDateAttribute()
    {
        return Carbon::parse($this->created_at)->diffForHumans();
    }

    function getIdHashAttribute()
    {
        return $this->encrypt($this->id);
    }
    public function scopeActive($q)
    {
        return $q->where('active', 1);
    }

    public function getUrlAttribute()
    {
        return route('site.showNews', $this->id . '-' . $this->slug);
    }

}
